local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    rolling_window: true
    width: 10.0
    height: 10.0

    plugins: ["static_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
      subscribe_to_updates: false


    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6             # metros alrededor de obstáculos
      cost_scaling_factor: 3.0          # control de caída exponencial
